- name: Installing and Running the Nginx server
  hosts: web
  become: yes # provoiding sudo access to install nginx
  tasks:
  - name: Install Nginx
  ansible.builtin.package:
    name: ntpdate
    state: present
    enabled: yes
 - name: Start service nginx, if not started
  ansible.builtin.service:
    name: nginx
    state: started

